# fly.toml app configuration file generated for onlytruth-backend
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "onlytruth-backend"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]

[env]
  PORT = "3001"
  NODE_ENV = "production"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false

    [http_service.checks.headers]
      X-Forwarded-Proto = "https"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

# Redis add-on for queue system
# Uncomment when ready to add Redis:
# [[services]]
#   http_checks = []
#   internal_port = 6379
#   processes = ["redis"]
#   protocol = "tcp"
#   script_checks = []
#
#   [[services.ports]]
#     port = 6379